server:
  port: 8080 # Random port for test

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: task-scheduler-service
              uri:
                lb://task-scheduler-service
              predicates:
                - Path=/api/jobs/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: jobServiceCircuitBreaker
                    fallbackUri: forward:/fallback/jobs
                - StripPrefix=1

            - id: worker-manager-service
              uri:
                lb://worker-manager-service
              predicates:
                - Path=/api/workers/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: workerServiceCircuitBreaker
                    fallbackUri: forward:/fallback/workers
                - StripPrefix=1
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true